
---

# Integrated Data Analysis Project (NumPy)

## Scenario

A hospital collected health data from 10 patients. Each patient has the following measurements:

* **Age**
* **Weight (kg)**
* **Systolic Blood Pressure**
* **Cholesterol Level**

This project performs a full **data analysis pipeline** on the dataset.

---

## 📊 Dataset

| Age | Weight (kg) | Blood Pressure | Cholesterol |
| --- | ----------- | -------------- | ----------- |
| 25  | 70          | 120            | 180         |
| 30  | 80          | 130            | 190         |
| 22  | 65          | 110            | 170         |
| 45  | 90          | 150            | 210         |
| 50  | 85          | 145            | 200         |
| 28  | 75          | 125            | 185         |
| 35  | 88          | 140            | 195         |
| 40  | 95          | 155            | 220         |
| 32  | 78          | 135            | 188         |
| 27  | 72          | 122            | 182         |

*Visualization suggestion: Add a heatmap of the dataset or a table image.*

---

## Part 1 — Basic Statistics 📈

**Objectives:**

* Calculate the **mean** of each column.
* Calculate the **standard deviation** of each column.
* Find **maximum and minimum values** for each feature.

*Visualization suggestion:* Use bar charts to compare mean, min, and max of each feature.

---

## Part 2 — Health Risk Detection ⚠️

**Identify high-risk patients with both conditions:**

* Blood Pressure > 140
* Cholesterol > 200

Return the **indices of these patients**.

*Visualization suggestion:* Highlight high-risk patients in a scatter plot (Blood Pressure vs Cholesterol).

---

## Part 3 — Feature Scaling 🔄

Apply **Min-Max Normalization** to scale all features to the range [0, 1]:

*Visualization suggestion:* Plot a side-by-side comparison of original vs normalized data.

---

## Part 4 — Correlation Analysis 🔗

Compute the **correlation matrix** to explore relationships between features:

* Age
* Weight
* Blood Pressure
* Cholesterol

*Visualization suggestion:* Use a heatmap to visualize correlations between all variables.

---

## Part 5 — Risk Score Calculation 💓

Define a **Health Risk Score** using normalized features:


**Tasks:**

1. Compute the risk score for each patient.
2. Identify the **top 3 highest-risk patients**.

*Visualization suggestion:* Use a horizontal bar chart to show risk scores and highlight the top 3 patients.

---

## 📌 Summary

This project demonstrates:

* **Basic statistical analysis** of health data
* **High-risk patient detection** based on multiple health metrics
* **Feature normalization** for consistent scaling
* **Correlation analysis** to understand relationships
* **Risk scoring** to prioritize patients

*Optional visuals:*

* Dataset table with highlighted top 3 risk patients
* Scatter plot of Blood Pressure vs Cholesterol
* Correlation heatmap
* Risk score bar chart

---


In [53]:
import numpy as np

In [54]:
data = [
[25,70,120,180],
[30,80,130,190],
[22,65,110,170],
[45,90,150,210],
[50,85,145,200],
[28,75,125,185],
[35,88,140,195],
[40,95,155,220],
[32,78,135,188],
[27,72,122,182]
]


In [55]:
# 1. Age
# 2. Weight
# 3. Blood Pressure
# 4. Cholesterol
data = np.array(data)
data

array([[ 25,  70, 120, 180],
       [ 30,  80, 130, 190],
       [ 22,  65, 110, 170],
       [ 45,  90, 150, 210],
       [ 50,  85, 145, 200],
       [ 28,  75, 125, 185],
       [ 35,  88, 140, 195],
       [ 40,  95, 155, 220],
       [ 32,  78, 135, 188],
       [ 27,  72, 122, 182]])

In [56]:
# Part 1
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
min_vals = np.min(data, axis=0)
max_vals = np.max(data, axis=0)
print(f'Mean = {mean}')
print(f'Std = {std}')
print(f'Min = {min_vals}')
print(f'Max = {max_vals}')

Mean = [ 33.4  79.8 133.2 192. ]
Std = [ 8.60464991  9.11921049 13.64404632 14.06413879]
Min = [ 22  65 110 170]
Max = [ 50  95 155 220]


In [57]:
# Part 2
bp = data[ : ,2]# column 3
chol = data[ : ,3]# column 4
risk_patients = np.where((bp > 140) & (chol > 200))[0]
print(risk_patients)

[3 7]


In [58]:
# Part 3
data_norm = (data - min_vals) / (max_vals - min_vals)
print(f'Data Normalization = \n\n{data_norm}')

Data Normalization = 

[[0.10714286 0.16666667 0.22222222 0.2       ]
 [0.28571429 0.5        0.44444444 0.4       ]
 [0.         0.         0.         0.        ]
 [0.82142857 0.83333333 0.88888889 0.8       ]
 [1.         0.66666667 0.77777778 0.6       ]
 [0.21428571 0.33333333 0.33333333 0.3       ]
 [0.46428571 0.76666667 0.66666667 0.5       ]
 [0.64285714 1.         1.         1.        ]
 [0.35714286 0.43333333 0.55555556 0.36      ]
 [0.17857143 0.23333333 0.26666667 0.24      ]]


In [65]:
# Part 4
corr_matrix = np.corrcoef(data, rowvar=False)
print(f'Correlation Matrix = \n\n{corr_matrix}')

Correlation Matrix = 

[[1.         0.82428912 0.89027261 0.82385126]
 [0.82428912 1.         0.97682959 0.96449352]
 [0.89027261 0.97682959 1.         0.97190207]
 [0.82385126 0.96449352 0.97190207 1.        ]]


In [74]:
# Part 5
weighted_norm = data[:,1]
bp_norm = data[:,2]
chol_norm = data[:,3]
risk_score = 0.3 * weighted_norm + 0.4 * bp_norm + 0.3 * chol_norm
print(f'Risk Score = {risk_score}')

Risk Score = [123.  133.  114.5 150.  143.5 128.  140.9 156.5 133.8 125. ]


In [92]:
top3 = np.argsort(risk_score)[-3:][::-1] # [start : end : incerement]

In [93]:
top3

array([7, 3, 4])

In [81]:
top3

array([2, 0, 9, 5, 1, 8, 6, 4, 3, 7])

In [111]:
s = [ 4 , 7 , 8 , 9 , 1 ,  2 , 3 ,10]
s[ : : -3] # 0 + 3 = 4 + 3

[10, 1, 7]